---
- hosts: all
  become: true
  tasks:
    - name: file
      file: dest=/home/ec2-user/test.txt state=touch
    - name: file
      file: dest=/home/testserver/test1.txt state=touch
    - name: copy file
      copy: 
        src: /home/ec2-user/test.txt 
        dest: /home/testserver/test1.txt
        remote_src: yes
    - name: debug
      debug: msg="This is a debug message"
    - name: shell
      shell: /bin/echo "Hello, world!"
    - name: yum
      yum: name={{item}} state=present
      with_items:
      - ntp
      - git
     
    - name: git
      git:
        repo: 'https://github.com/Supreet14/github_basics.git'
        dest: /home/ec2-user/test
    - name: cli
      command: docker --version
      
    - name: Rollback
      command: cat /etc/issue
      register: output
    - debug: var=output
    - name: Rollback to a specific version
      command: "{{ item }}"
      with_items:
      - apt-get install -y version=1.0.0-1
      - apt-get install -y version=2.0.0-1
      - apt-get install -y version=3.0.0-1
