---
- hosts: all
  become: true
  tasks:
    - name: file
      file: dest=- name: file
      file: dest=/home/ec2-user/test.txt state=touch state=touch
    - name: file
      file: dest=/home/testserver/test1.txt state=touch
    - name: copy file
      copy: 
        src: /home/ec2-user/test.txt 
        dest: /home/testserver/test1.txt
        remote_src: yes
    - name: debug
      debug: msg="This is a debug message"
    - name: shell
      shell: /bin/echo "Hello, world!"
    - name: yum
      yum: name={{item}} state=present
      with_items:
      - ntp
      - git
      - cli
    - name: lineinfile
      lineinfile: dest=/home/ec2-user/test.txt 
      state: present
    - name: archive
      archive: path=/etc/ansible/src dest=/etc/ansible/dest format=gz
    - name: git
      git: repo=https://github.com/ansible/ansible.git dest=/etc/ansible/checkouts/ansible version=release2.1.1.0
    - name: cli
      command: ansible --version
