---
- hosts: all
  connection: local
  become: true
  tasks:
    - name: Include
      include: ansible.yml
    - name: file
      command: "{{ ansible_env.HOME }}"
      register: output
    - debug: var=output
