---
- hosts: all
  become: true
  tasks:
    - name: Archive
      archive:
        path: /home/ec2-user/*
        dest: /home/ec2-user/test.zip
        format: zip
    - name: Include
      include: ansible.yml

